[package]

name = "Docker_DLC"
version = "1.0.11-beta"
edition = "2024"

[dependencies]

dlc = "=0.8.0"
dlc-manager = "=0.7.1"
dlc-messages = "=0.8.0"
rustls = "0.23.35"
idna = "1.1.0"
openssl = "0.10.75"
ring = "0.17.14"
tokio = "1.48.0"
crossbeam = "0.8.4"
async-trait = "0.1.89"
log = "0.4.27"
thiserror = "2.0.17"
env_logger = "0.11.8"

[lib]

path = "src/main.rs"