[package]

name = "Docker_DLC"
version = "1.0.8-beta"
edition = "2021"

[dependencies]

dlc = "=0.7.1"
dlc-manager = "=0.7.1"
dlc-messages = "=0.7.1"
ddk = "0.0.14"
rustls = "0.23.23"
idna = "1.0.0"
openssl = "0.10.71"